import { DocumentConfig } from './types';

export const DEFAULT_MARKDOWN = `# Project Proposal: DocuMorph

## 1. Introduction
This document outlines the architecture for **DocuMorph**, a client-side tool for converting Markdown to formatted Word documents.

![Abstract Architecture](https://avatars.githubusercontent.com/u/36368107)

### Key Features
* Real-time preview
* Customizable styling
* Equation support ($E = mc^2$)

> "Design is not just what it looks like and feels like. Design is how it works." — Steve Jobs

## 2. Methodology
We utilize abstract syntax tree parsing to map HTML nodes directly to OpenXML formats.

### Math Formula
The Gaussian Integral is defined as:
$$
\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}
$$

### Code Example

\`\`\`javascript
const convert = (input) => {
  return process(input);
};
\`\`\`

---

*Generated by DocuMorph*
`;

export const DEFAULT_CONFIG: DocumentConfig = {
  h1: {
    fontFamily: 'Inter',
    fontSize: 24,
    color: '#1e293b',
    bold: true,
    italic: false,
    alignment: 'left',
    marginTop: 24,
    marginBottom: 12,
  },
  h2: {
    fontFamily: 'Inter',
    fontSize: 18,
    color: '#334155',
    bold: true,
    italic: false,
    alignment: 'left',
    marginTop: 18,
    marginBottom: 8,
  },
  h3: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: '#475569',
    bold: true,
    italic: false,
    alignment: 'left',
    marginTop: 12,
    marginBottom: 6,
  },
  p: {
    fontFamily: 'Merriweather',
    fontSize: 11,
    color: '#374151',
    bold: false,
    italic: false,
    alignment: 'justify',
    marginTop: 0,
    marginBottom: 10,
  },
  quote: {
    fontFamily: 'Merriweather',
    fontSize: 11,
    color: '#4b5563',
    bold: false,
    italic: true,
    alignment: 'left',
    marginTop: 12,
    marginBottom: 12,
  },
  code: {
    fontFamily: 'JetBrains Mono',
    fontSize: 10,
    color: '#dc2626',
    bold: false,
    italic: false,
    alignment: 'left',
    marginTop: 10,
    marginBottom: 10,
  },
  link: {
    color: '#0284c7',
    underline: true,
  },
};
